-- 문제
-- 여행 취소율 구하기
-- https://chaemi720.tistory.com/351

SELECT REQUEST_AT AS 'Day'
     , ROUND(CANCEL_COUNT/TOTAL_COUNT,2) AS 'Cancellation Rate'
FROM (
    SELECT REQUEST_AT
        , SUM(CASE WHEN STATUS != 'COMPLETED' THEN 1 ELSE 0 END) AS CANCEL_COUNT
        , COUNT(*) AS TOTAL_COUNT
    FROM TRIPS AS T
        INNER JOIN USERS AS UC
            ON T.CLIENT_ID = UC.USERS_ID
        INNER JOIN USERS AS UD
            ON T.DRIVER_ID = UD.USERS_ID
    WHERE T.REQUEST_AT BETWEEN '2013-10-01' AND '2013-10-03'
        AND UC.BANNED = 'NO' AND UD.BANNED = 'NO'
    GROUP BY REQUEST_AT
) T;