CREATE PROCEDURE solution()
BEGIN
	/* Write your SQL here. Terminate each statement with a semicolon. */
	SELECT (DAYOFWEEK(MISCHIEF_DATE)+5)%7 AS WEEKDAY
		, MISCHIEF_DATE
		, AUTHOR
		, TITLE
	FROM MISCHIEF
	ORDER BY WEEKDAY, FIELD(AUTHOR, 'HUEY', 'DEWEY', 'LOUIE'), MISCHIEF_DATE, TITLE ;
END