CREATE PROCEDURE solution()
BEGIN
	/* Write your SQL here. Terminate each statement with a semicolon. */
	SELECT COUNT(*) AS NUMBER_OF_NULLS
	FROM DEPARTMENTS
	WHERE DESCRIPTION IS NULL
		OR LOWER(TRIM(DESCRIPTION)) = 'NULL'
		OR LOWER(TRIM(DESCRIPTION)) = 'NIL'
		OR LOWER(TRIM(DESCRIPTION)) = '-';
END