CREATE PROCEDURE solution()
BEGIN
	/* Write your SQL here. Terminate each statement with a semicolon. */
	WITH WIN_LOSE AS (
	SELECT SUM(CASE WHEN FIRST_TEAM_SCORE > SECOND_TEAM_SCORE THEN 1 ELSE 0 END) AS FIRST_WIN_CNT
		, SUM(CASE WHEN FIRST_TEAM_SCORE < SECOND_TEAM_SCORE THEN 1 ELSE 0 END) AS SECOND_WIN_CNT
		, SUM(FIRST_TEAM_SCORE - SECOND_TEAM_SCORE) AS SCORE_DIFF
		, SUM(CASE WHEN MATCH_HOST = 2 THEN FIRST_TEAM_SCORE ELSE 0 END) AS FIRST_SCORE_OF_2
		, SUM(CASE WHEN MATCH_HOST = 1 THEN SECOND_TEAM_SCORE ELSE 0 END) AS SECOND_SCORE_OF_1
	FROM SCORES
	)
	
	SELECT CASE
				WHEN FIRST_WIN_CNT > SECOND_WIN_CNT THEN 1 
				WHEN FIRST_WIN_CNT < SECOND_WIN_CNT THEN 2
				WHEN SCORE_DIFF > 0 THEN 1
				WHEN SCORE_DIFF < 0 THEN 2
				WHEN FIRST_SCORE_OF_2 > SECOND_SCORE_OF_1 THEN 1
				WHEN FIRST_sCORE_OF_2 < SECOND_SCORE_OF_1 THEN 2
				ELSE 0
			END AS WINNER
	FROM WIN_LOSE;
END