CREATE PROCEDURE solution()
BEGIN
	/* Write your SQL here. Terminate each statement with a semicolon. */
	WITH RECURSIVE ALARM AS (
		SELECT INPUT_DATE AS ALARM_DATE
			, INPUT_DATE AS END_DATE
		FROM USERINPUT
		
		UNION ALL
		
		SELECT DATE_ADD(ALARM_DATE, INTERVAL 7 DAY) AS ALARM_DATE
			, END_DATE
		FROM ALARM
		WHERE YEAR(DATE_ADD(ALARM_DATE, INTERVAL 7 DAY)) = YEAR(END_DATE)
	)
	
	SELECT ALARM_DATE FROM ALARM;
END